export const LATEX_PREAMBLE = `
\\documentclass[11pt,a4paper]{article}
\\usepackage[utf8]{inputenc}
\\usepackage{geometry}
\\usepackage{xcolor}
\\usepackage{hyperref}
\\usepackage{titlesec}
\\usepackage{enumitem}
\\usepackage{fancyhdr}
\\usepackage{lastpage}
\\usepackage{parskip}

% Geometry setup
\\geometry{
    a4paper,
    total={170mm,257mm},
    left=20mm,
    top=20mm,
}

% Colors
\\definecolor{primary}{RGB}{0, 75, 120}
\\definecolor{secondary}{RGB}{100, 100, 100}

% Typos settings
\\titleformat{\\section}
  {\\normalfont\\Large\\bfseries\\color{primary}}{\\thesection}{1em}{}
\\titleformat{\\subsection}
  {\\normalfont\\large\\bfseries\\color{primary}}{\\thesubsection}{1em}{}
\\titleformat{\\subsubsection}
  {\\normalfont\\normalsize\\bfseries\\color{secondary}}{\\thesubsubsection}{1em}{}

% Hyperlink setup
\\hypersetup{
    colorlinks=true,
    linkcolor=primary,
    filecolor=magenta,      
    urlcolor=primary,
    pdftitle={Research Report},
}

% Header and Footer
\\pagestyle{fancy}
\\fancyhf{}
\\rhead{\\color{secondary} Generated by Omni-research Agent}
\\lhead{\\color{primary} \\textbf{Project Report}}
\\rfoot{Page \\thepage \\hspace{1pt} of \\pageref{LastPage}}

\\setlength{\\parindent}{0pt}
\\setlength{\\parskip}{0.8em}

\\begin{document}
`;

export const LATEX_POSTAMBLE = `
\\end{document}
`;
