// ============================================================================
// FILE: src/lib/config/academic-seeds.ts
// (Auto-expanded with labs from Application-Tracker-Winter_Spring-2025-2026-3.xlsx)
// ============================================================================

export type AcademicSeedTarget = { label: string; url: string };

// --- Manually curated seeds (original list) ---
const CURATED_SEED_TARGETS: AcademicSeedTarget[] = [
  // --- US Universities ---
  { label: 'Harvard SEAS news', url: 'https://www.seas.harvard.edu/news' },
  { label: 'Harvard CS (SEAS) directory', url: 'https://www.seas.harvard.edu/computer-science' },
  { label: 'MIT CSAIL news', url: 'https://www.csail.mit.edu/news' },
  { label: 'Stanford AI Lab news', url: 'https://ai.stanford.edu/blog/' },
  { label: 'Berkeley AI Research (BAIR) blog', url: 'https://bair.berkeley.edu/blog/' },
  { label: 'CMU SCS News', url: 'https://www.cs.cmu.edu/news' },
  { label: 'Princeton CS News', url: 'https://www.cs.princeton.edu/news' },
  { label: 'Cornell CIS News', url: 'https://cis.cornell.edu/news' },
  { label: 'UW Allen School News', url: 'https://news.cs.washington.edu/' },
  { label: 'Georgia Tech Computing News', url: 'https://www.cc.gatech.edu/news' },
  { label: 'Caltech IST News', url: 'https://www.ist.caltech.edu/news/' },
  { label: 'Columbia Engineering News', url: 'https://www.engineering.columbia.edu/news' },
  { label: 'UPenn Engineering News', url: 'https://blog.seas.upenn.edu/' },
  { label: 'Yale SEAS News', url: 'https://seas.yale.edu/news-events/news' },
  { label: 'Michigan CSE News', url: 'https://cse.engin.umich.edu/news/' },
  { label: 'UT Austin CS News', url: 'https://www.cs.utexas.edu/news' },
  { label: 'UIUC CS News', url: 'https://cs.illinois.edu/news' },
  { label: 'UCSD CSE News', url: 'https://cse.ucsd.edu/about/news' },
  { label: 'UCLA Engineering News', url: 'https://samueli.ucla.edu/newsroom/' },
  { label: 'Maryland CS News', url: 'https://www.cs.umd.edu/news' },
  { label: 'Toronto CS News', url: 'https://web.cs.toronto.edu/news-events' },

  // --- European Universities ---
  { label: 'Oxford CS News', url: 'https://www.cs.ox.ac.uk/news/' },
  { label: 'Cambridge Computer Lab News', url: 'https://www.cst.cam.ac.uk/news' },
  { label: 'ETH Zurich Inf News', url: 'https://inf.ethz.ch/news-and-events.html' },
  { label: 'EPFL IC News', url: 'https://ic.epfl.ch/news-events/' },
  { label: 'TUM Informatics News', url: 'https://www.cit.tum.de/en/cit/news/' },
  { label: 'Max Planck Institute for Informatics', url: 'https://www.mpi-inf.mpg.de/news/' },
  { label: 'Imperial College Computing News', url: 'https://www.imperial.ac.uk/computing/news/' },
  { label: 'UCL Computer Science News', url: 'https://www.ucl.ac.uk/computer-science/news' },
  { label: 'Edinburgh Informatics News', url: 'https://www.ed.ac.uk/informatics/news-events' },
  { label: 'KTH EECS News', url: 'https://www.kth.se/en/eecs/nyheter' },

  // --- Asian Universities ---
  { label: 'Tsinghua IIIS News', url: 'https://iiis.tsinghua.edu.cn/en/news/' },
  { label: 'Peking University EECS', url: 'https://eecs.pku.edu.cn/english/News_Events/News.htm' },
  { label: 'NUS Computing News', url: 'https://www.comp.nus.edu.sg/news/' },
  { label: 'NTU SCSE News', url: 'https://www.ntu.edu.sg/scse/news-events/news' },
  { label: 'HKUST CSE News', url: 'https://cse.hkust.edu.hk/news/' },
  { label: 'KAIST CS News', url: 'https://cs.kaist.ac.kr/news/news' },
  { label: 'Tokyo University CS News', url: 'https://www.i.u-tokyo.ac.jp/news/index_e.shtml' },

  // --- Corporate & Independent Research ---
  { label: 'Google DeepMind Blog', url: 'https://deepmind.google/discover/blog/' },
  { label: 'OpenAI Research', url: 'https://openai.com/research' },
  { label: 'Microsoft Research Blog', url: 'https://www.microsoft.com/en-us/research/blog/' },
  { label: 'Meta AI Blog', url: 'https://ai.meta.com/blog/' },
  { label: 'NVIDIA Blog', url: 'https://blogs.nvidia.com/blog/category/deep-learning/' },
  { label: 'AWS Machine Learning Blog', url: 'https://aws.amazon.com/blogs/machine-learning/' },
  { label: 'Apple Machine Learning Research', url: 'https://machinelearning.apple.com/' },
  { label: 'Uber Engineering', url: 'https://www.uber.com/blog/engineering/' },
  { label: 'Netflix TechBlog', url: 'https://netflixtechblog.com/' },
];

// --- Auto-added labs from your tracker (non-email URLs only) ---
const TRACKER_LAB_SEED_TARGETS: AcademicSeedTarget[] = [
  { label: "Kempner Institute", url: "https://kempnerinstitute.harvard.edu" },
  { label: "DtAK Lab | Finale Doshi-Velez", url: "https://dtak.github.io" },
  { label: "Lukin Group | Mikhail Lukin", url: "https://lukin.physics.harvard.edu" },
  { label: "Harvard Quantum Initiative (HQI)", url: "https://hqi.harvard.edu" },
  { label: "Wyss Institute | Donald Ingber", url: "https://wyss.harvard.edu" },
  { label: "Harvard Stem Cell Institute (HSCI)", url: "https://hsci.harvard.edu" },
  { label: "Center for Brain Science (CBS)", url: "https://cbs.harvard.edu" },
  { label: "Lichtman Lab | Jeff Lichtman", url: "https://lichtman.harvard.edu" },
  { label: "Church Lab | George Church", url: "https://church.harvard.edu" },
  { label: "Center for Systems Biology | Marc Kirschner", url: "https://sysbio.med.harvard.edu" },
  { label: "Laboratory of Systems Pharmacology | Peter Sorger", url: "https://sorger.med.harvard.edu" },
  { label: "Boaz Barak", url: "http://s://www.boazbarak.org/" },
  { label: "MSRP (Summer Research Program)", url: "https://msrp.mit.edu" },
  { label: "MISTI (Global Research)", url: "https://misti.mit.edu" },
  { label: "Lincoln Laboratory", url: "https://jhuapl.edu" },
  { label: "Deisseroth Lab | Karl Deisseroth", url: "https://deisseroth.stanford.edu" },
  { label: "Shenoy/Henderson Lab | Jaimie Henderson", url: "https://henderson-lab.stanford.edu" },
  { label: "Center for Research on FM | Percy Liang", url: "https://crfm.stanford.edu" },
  { label: "Human-Centered AI | Fei-Fei Li", url: "https://hai.stanford.edu" },
  { label: "Machine Learning Group | Andrew Ng", url: "https://ml.stanford.edu" },
  { label: "Stanford Robotics Lab | Oussama Khatib", url: "https://robotics.stanford.edu" },
  { label: "Stanford NLP Group | Christopher Manning", url: "https://nlp.stanford.edu" },
  { label: "Stanford Vision Lab | Li Fei-Fei", url: "https://vision.stanford.edu" },
  { label: "Genetics Bioscience | Michael Snyder", url: "https://snyder.stanford.edu" },
  { label: "IQIM Quantum | John Preskill", url: "https://iqim.caltech.edu" },
  { label: "TAPIR Astrophysics | Sterl Phinney", url: "https://tapir.caltech.edu" },
  { label: "LIGO Lab | Rana Adhikari", url: "https://ligo.caltech.edu" },
  { label: "Division of Biology | Kai Zinn", url: "https://biology.caltech.edu" },
  { label: "Jet Propulsion Lab | NASA", url: "https://jpl.nasa.gov" },
  { label: "Tsao Lab | Doris Tsao", url: "https://tsao-lab.berkeley.edu" },
  { label: "Gallant Lab | Jack Gallant", url: "https://gallantlab.org" },
  { label: "RISELab | Ion Stoica", url: "https://riselab.org" },
  { label: "Vision & Learning | Jitendra Malik", url: "https://malik-lab.berkeley.edu" },
  { label: "Berkeley AI Lab (BAIR) | Stuart Russell", url: "https://bair.berkeley.edu" },
  { label: "Neurodynamics Lab | Bruno Olshausen", url: "https://redwood.berkeley.edu" },
  { label: "Robotics Institute | Martial Hebert", url: "https://ri.cmu.edu" },
  { label: "Machine Learning Department | Tom Mitchell", url: "https://ml.cmu.edu" },
  { label: "School of Computer Science | Dean Raj Reddy", url: "https://cs.cmu.edu" },
  { label: "AI and Language Lab | Yonatan Bisk", url: "https://argmin.net" },
  { label: "Biomedical ML | Zhenming Liu", url: "https://cmu.edu/bioml" },
  { label: "Cornell AI Lab | Carla Gomes", url: "https://ai.cornell.edu" },
  { label: "Cornell Center for Astrophysics", url: "https://astro.cornell.edu" },
  { label: "Bowers College of Computing & IT", url: "https://computing.cornell.edu" },
  { label: "Cornell Neuroscience", url: "https://neuroscience.cornell.edu" },
  { label: "Cornell Biomedical Engineering | David Needham", url: "https://bme.cornell.edu" },
  { label: "Cornell Computational Biology | Bart Selman", url: "https://cs.cornell.edu" },
  { label: "Penn Engineering (AI/ML) | Nikolaos Pappas", url: "https://seas.upenn.edu" },
  { label: "Penn Neuroscience | Eve Marder (Visiting)", url: "https://neuro.upenn.edu" },
  { label: "Penn Medicine AI Lab | Benjamin Vogelstein", url: "https://vogelstein.upenn.edu" },
  { label: "Perelman School of Medicine | (Biomedical)", url: "https://med.upenn.edu" },
  { label: "Data Science Institute | Garud Iyengar", url: "https://datascience.columbia.edu" },
  { label: "ARNI (AI Institute)", url: "https://arni-institute.org" },
  { label: "Zuckerman Institute | Rui Costa", url: "https://shohamy-lab.org" },
  { label: "Columbia Nano Initiative", url: "https://cni.columbia.edu" },
  { label: "MINDS Institute", url: "https://minds.jhu.edu" },
  { label: "Kavli NDI", url: "https://kavli.jhu.edu" },
  { label: "Duke AI Lab | Lingling Chen", url: "https://ai.duke.edu" },
  { label: "Pratt School of Engineering", url: "https://pratt.duke.edu" },
  { label: "Duke Center for Brain Science", url: "https://brain.duke.edu" },
  { label: "Siebel School of Computing & Data Science", url: "https://siebelschool.illinois.edu" },
  { label: "Coordinated Science Lab | Hosung Park", url: "https://csl.illinois.edu" },
  { label: "UIUC AI Research Lab | Paris Smaragdis", url: "https://asl.illinois.edu" },
  { label: "Illinois Bioengineering | Andrew Gewirth", url: "https://biophotonics.illinois.edu" },
  { label: "Georgia Tech AI Lab | Thad Starner", url: "https://ai.gatech.edu" },
  { label: "School of Interactive Computing", url: "https://ic.gatech.edu" },
  { label: "Wallace H. Coulter Department | Hang Lu", url: "https://bme.gatech.edu" },
  { label: "Chang Lab | Edward Chang", url: "https://changlab.ucsf.edu" },
  { label: "McDevitt Lab | Todd McDevitt", url: "https://mcdevittlab.org" },
  { label: "UCSF Brain Initiative | Loren Frank", url: "https://braininitiative.ucsf.edu" },
  { label: "Princeton Neuro Inst (PNI) | John Hopfield", url: "https://pni.princeton.edu" },
  { label: "Princeton CS (ML Area) | Sanjeev Arora", url: "https://cs.princeton.edu" },
  { label: "Center for Neural Science | NYU", url: "https://cns.nyu.edu" },
  { label: "Center for Data Science | NYU | Yann LeCun", url: "https://cds.nyu.edu" },
  { label: "UT Austin AI Lab | Scott Niekum", url: "https://www2.cs.utexas.edu/~ai-lab" },
  { label: "Searle AI Institute | Peter Stone", url: "https://www2.cs.utexas.edu/~AustinVilla" },
  { label: "UT Brain Initiative", url: "https://utbraininitiative.org" },
  { label: "Paul G. Allen School of CS", url: "https://cs.washington.edu" },
  { label: "UW Center for Sensorimotor Neural Engineering", url: "https://csne.washington.edu" },
  { label: "Ubiquitous Computing Lab | Shyam Gollakota", url: "https://ubicomplab.cs.washington.edu" },
  { label: "Tsinghua AI Lab | Andrew Ng (Affiliated)", url: "https://tsinghua.edu.cn/ai" },
  { label: "Department of Computer Science", url: "https://dcs.tsinghua.edu.cn" },
  { label: "Institute for Artificial Intelligence | Hai Yang", url: "https://iail.tsinghua.edu.cn" },
  { label: "School of Life Sciences | Yiming Cheng", url: "https://sls.tsinghua.edu.cn" },
  { label: "Tsinghua Quantum Lab | Pan Jianwei", url: "https://quantum.tsinghua.edu.cn" },
  { label: "Peking AI Lab | Michael I. Jordan (Affiliated)", url: "https://pku.edu.cn/ai" },
  { label: "School of Artificial Intelligence", url: "https://sai.pku.edu.cn" },
  { label: "Center for Quantitative Biology | Chao Tang", url: "https://cqb.pku.edu.cn" },
  { label: "Institute of Brain Sciences | Hailan Hu", url: "https://ibs.pku.edu.cn" },
  { label: "School of Computer Science | (AI Focus)", url: "https://sist.shanghaitech.edu.cn" },
  { label: "Institute of Biomedical Sciences | Guo Zhang", url: "https://ibs.shanghaitech.edu.cn" },
  { label: "Fudan Institute of Advanced Study", url: "https://fias.fudan.edu.cn" },
  { label: "School of Computer Science", url: "https://cs.fudan.edu.cn" },
  { label: "NUS School of Computing | Xavier Bresson", url: "https://comp.nus.edu.sg" },
  { label: "NUS Institute of AI | (Joint Centre)", url: "https://nus.edu.sg/ai" },
  { label: "NUS BioInformatics & Data Science", url: "https://bioinfo.nus.edu.sg" },
  { label: "Centre for Quantum Technologies | Peter Knight", url: "https://quantech.nus.edu.sg" },
  { label: "NTU School of Computer Science & Engineering | Bo An", url: "https://scse.ntu.edu.sg" },
  { label: "NTU S. Rajaratnam School of International Studies", url: "https://rsis.ntu.edu.sg" },
  { label: "AI Singapore (AI-IS) | (AISG Partner Lab)", url: "https://aisingapore.org" },
  { label: "Cavendish Lab", url: "https://cambridge.ac.uk" },
  { label: "Department of Computer Science & Technology", url: "https://cam.ac.uk/cs" },
  { label: "Cambridge Centre for AI Safety", url: "https://ai-safety.org" },
  { label: "Department of Psychology | Eleanor Maguire", url: "https://psychology.cam.ac.uk" },
  { label: "Department of Applied Mathematics | Stephen Tobias", url: "https://damtp.cam.ac.uk" },
  { label: "Medical Research Council (MRC) Labs", url: "https://mrc-lmb.cam.ac.uk" },
  { label: "Future of Humanity Institute | Nick Bostrom", url: "https://fhi.ox.ac.uk" },
  { label: "Department of Computer Science", url: "https://cs.ox.ac.uk" },
  { label: "Computational Biology Research Group", url: "https://compbio.ox.ac.uk" },
  { label: "Oxford Brookes University (AI Lab)", url: "https://brookes.ac.uk" },
  { label: "Department of Computing | Yike Guo", url: "https://imperial.ac.uk/computing" },
  { label: "Institute for Mathematical Sciences", url: "https://imperial.ac.uk/maths" },
  { label: "Bio-inspired Materials | Molly Stevens", url: "https://imperial.ac.uk" },
  { label: "Department of Materials Science | Robert Sinclair", url: "https://imperial.ac.uk/materials" },
  { label: "Gatsby Unit | Maneesh Sahani", url: "https://gatsby.ucl.ac.uk" },
  { label: "Department of Computer Science", url: "https://ucl.ac.uk/cs" },
  { label: "UCL Neuroscience | Lisa Gentet", url: "https://ucl.ac.uk/neuroscience" },
  { label: "School of Informatics | Amos Storkey", url: "https://ed.ac.uk/informatics" },
  { label: "Institute for Adaptive and Neural Computation", url: "https://ed.ac.uk/ianc" },
  { label: "Robotics & Autonomous Systems Group", url: "https://ed.ac.uk/robots" },
  { label: "CERN (ATLAS/CMS)", url: "https://cern.ch" },
  { label: "CERN Theory Division | Rolf Heuer", url: "https://home.cern/theory" },
  { label: "CERN Computing & Data Centre", url: "https://home.cern/computing" },
  { label: "Janelia Research Campus", url: "https://janelia.org" },
  { label: "Anthropic | Dario Amodei", url: "https://anthropic.com" },
  { label: "Google DeepMind | Demis Hassabis", url: "https://deepmind.google" },
  { label: "Meta FAIR | Yann LeCun", url: "https://facebook.com/ai" },
  { label: "OpenAI Research | Jakub Pachocki", url: "https://openai.com" },
  { label: "D. E. Shaw Research | David Shaw", url: "https://deshawresearch.com" },
  { label: "Jane Street Research", url: "https://janestreet.com" },
  { label: "Citadel Securities | Peng Zhao", url: "https://citadelgroup.com" },
  { label: "Microsoft Research | Eric Horvitz", url: "https://microsoft.com/research" },
  { label: "NVIDIA Research | Bill Dally", url: "https://nvidia.com/research" },
  { label: "Amazon AGI | Rohit Prasad", url: "https://amazon.com/ai" },
  { label: "X Development (Google X) | Astro Teller", url: "https://x.company" },
  { label: "Boston Consulting Group (BCG) AI Lab", url: "https://bcg.com/ai" },
  { label: "NSF REU", url: "https://nsf.gov/reu" },
  { label: "Amgen Scholars", url: "https://amgenscholars.com" },
  { label: "Goldwater Scholarship", url: "https://goldwater.org" },
  { label: "NSF GRFP", url: "https://nsf.gov/grfp" },
  { label: "Rhodes Scholarship", url: "https://rhodeshouse.ox.ac.uk" },
  { label: "Marshall Scholarship", url: "https://marshallscholarship.org" },
  { label: "Churchill Scholarship", url: "https://churchillscholarship.org" },
  { label: "Hertz Fellowship", url: "https://hertzfoundation.org" },
  { label: "DoD NDSEG", url: "https://ndseg.asee.org" },
  { label: "HHMI International Student Research Fellowships", url: "https://hhmi.org" },
  { label: "Royal Commission for the Exhibition of 1851 Awards", url: "https://royalcommission1851.org.uk" },
  { label: "Nucleate", url: "http://s://nucleate.xyz/" },
  { label: "Activate Fellowship", url: "http://s://www.activate.org/" },
  { label: "Greentown Labs", url: "http://s://greentownlabs.com/" },
  { label: "MassChallenge", url: "http://s://masschallenge.org/" },
  { label: "UMass M2D2", url: "http://s://www.uml.edu/research/m2d2/" },
  { label: "DRIVe (BARDA)", url: "http://s://drive.hhs.gov/about.html" },
  { label: "MassVentures Acorn Innovation Grant", url: "http://s://www.mass-ventures.com/mvcapital/acorn" },
  { label: "MIT The Engine — Blueprint", url: "http://s://engine.xyz/network/blueprint-s2023" },
  { label: "U.S. Tech Force (Early‑Career AI/Tech Corps)", url: "http://s://techforce.gov/" },
  { label: "Genesis Mission (National AI for Science)", url: "http://s://www.whitehouse.gov/presidential-actions/2025/11/launching-the-genesis-mission/" },
  { label: "AI Action Plan / AI.gov Programs", url: "http://s://www.ai.gov/" },
  { label: "Federal AI & Quantum R&D Priority Boost", url: "http://s://www.nature.com/articles/d41586-025-04108-y" },
  { label: "Albany Nanotech Complex (SUNY Poly)", url: "http://s://sunypoly.edu/research/albany-nanotech-complex.html" },
  { label: "Acquillius", url: "http://s://www.aquillius.com/" },
  { label: "Artisan’s Asylum", url: "http://s://www.artisansasylum.com/" },
  { label: "Baltimore Underground Science Space (BUGSS)", url: "http://s://bugssonline.org/" },
  { label: "Berkeley Marvell Nanolab", url: "http://s://nanolab.berkeley.edu/" },
  { label: "BioCurious", url: "http://s://biocurious.org/" },
  { label: "BioLabs – Tufts Launchpad", url: "http://s://www.biolabs.io/locations" },
  { label: "Bolt – Boston", url: "http://s://bolt.io/" },
  { label: "Biodidact", url: "http://biodidact.net/" },
  { label: "Biotech Without Borders", url: "http://s://biotechwithoutborders.org/" },
  { label: "BosLab", url: "http://s://www.boslab.org/" },
  { label: "bwtech @ UMBC (Biotech)", url: "http://s://bwtech.umbc.edu/incubators/biotech/" },
  { label: "Centech", url: "http://s://centech.co/en/" },
  { label: "Counter Culture Labs", url: "http://s://www.counterculturelabs.org/" },
  { label: "Dallas Makerspace", url: "http://s://dallasmakerspace.org/" },
  { label: "District 3", url: "http://s://district3.co/" },
  { label: "Genspace", url: "http://s://www.genspace.org/" },
  { label: "Halifax Makerspace", url: "http://s://halifaxmakerspace.org/" },
  { label: "Incubator Art Lab", url: "http://s://incubatorartlab.com/" },
  { label: "IQC NanoFab Lab (Waterloo)", url: "http://s://uwaterloo.ca/institute-for-quantum-computing/about/facilities-and-labs" },
  { label: "InterAccess", url: "http://s://interaccess.org/" },
  { label: "JLABS @ LabCentral", url: "http://s://jnjinnovation.com/locations/jlabs/jlabs-labcentral" },
  { label: "JLABS @ NYC", url: "http://s://jnjinnovation.com/locations/jlabs/jlabs-nyc" },
  { label: "JLABS @ MBC BioLabs", url: "http://s://jnjinnovation.com/locations/jlabs/jlabs-mbc-biolabs" },
  { label: "JLABS @ San Diego", url: "http://s://jnjinnovation.com/locations/jlabs/jlabs-san-diego" },
  { label: "JLABS @ SSF", url: "http://s://jnjinnovation.com/locations/jlabs/jlabs-ssf" },
  { label: "JLABS @ TMC", url: "http://s://jnjinnovation.com/locations/jlabs/jlabs-tmc" },
  { label: "JLABS @ Toronto", url: "http://s://jnjinnovation.com/locations/jlabs/jlabs-toronto" },
  { label: "JLABS @ Washington DC", url: "http://s://jnjinnovation.com/locations/jlabs/jlabs-washington-dc" },
  { label: "La Jolla Bio Lab (IDEA Lab)", url: "http://s://www.lajollalibrary.org/idea-lab" },
  { label: "LabCentral", url: "http://s://labcentral.org/" },
  { label: "London Biohackspace", url: "http://s://biohackspace.org/" },
  { label: "MakerSpace Charlotte", url: "http://s://www.makerspacecharlotte.org/" },
  { label: "MakerWorks", url: "http://s://www.maker-works.com/" },
  { label: "Molecular Foundry (LBNL)", url: "http://s://foundry.lbl.gov/" },
  { label: "NewLab", url: "http://s://www.newlab.com/" },
  { label: "Noisebridge", url: "http://s://www.noisebridge.net/wiki/Noisebridge" },
  { label: "North Forge Fabrication Lab", url: "http://s://northforge.ca/support-services/fabrication-lab/" },
  { label: "NYC Resistor", url: "http://s://www.nycresistor.com/" },
  { label: "Open Science Network", url: "http://www.opensciencenet.org/" },
  { label: "Ottawa Bio Science", url: "http://specyal.com/diybio/" },
  { label: "Protospace", url: "http://s://protospace.ca/" },
  { label: "Pumping Station: One", url: "http://s://pumpingstationone.org/" },
  { label: "QB3", url: "http://s://qb3.org/" },
  { label: "Rensselaer cMDIS", url: "http://s://cmdis.rpi.edu/facilities-equipment" },
  { label: "Science Discovery Zone", url: "http://s://decadeofdiscovery.torontomu.ca/community/the-business-of-innovation" },
  { label: "Scihouse", url: "http://s://www.scihouse.space/" },
  { label: "SoundBio Lab", url: "http://s://www.sound.bio/" },
  { label: "Stanford Nanofabrication Facility", url: "http://s://snf.stanford.edu/" },
  { label: "Teardown Library – San Francisco", url: "http://s://teardownlibrary.com/" },
  { label: "The Makery", url: "http://s://www.nycmakery.com/" },
  { label: "TinkerMill", url: "http://s://tinkermill.org/" },
  { label: "UH Nanofabrication Facility (UHNF)", url: "http://s://uhnf.egr.uh.edu/" },
  { label: "Vancouver Hack Space", url: "http://s://vanhack.ca/" },
  { label: "Velocity", url: "http://s://velocityincubator.com/" },
  { label: "Badass Labs", url: "http://s://badasslabs.org/" },
  { label: "Daybreak Labs", url: "http://s://daybreaklabs.io/" },
  { label: "Bonneville Labs", url: "http://s://bonnevillelabs.com/" },
  { label: "Spalding Lab (Kirsty Spalding)", url: "http://s://www.spaldinglab.org/" },
  { label: "Kanold Lab", url: "http://s://kanoldlab.com" },
  { label: "Allen Institute for Neural Dynamics", url: "http://s://alleninstitute.org/division/neural-dynamics/" },
  { label: "Orsborn Lab", url: "http://s://www.ece.uw.edu/people/amy-orsborn/" },
  { label: "Noble‑Haeusslein (Noble) Lab", url: "http://s://sites.utexas.edu/noble-lab/" },
  { label: "Cold Spring Harbor Laboratory – Neuroscience", url: "http://s://www.cshl.edu/research/neuroscience/" },
  { label: "Svoboda Lab", url: "http://s://www.janelia.org/svoboda-lab" },
  { label: "Laboratory of Evolutionary Design | Brian Hie", url: "http://s://evodesign.org" },
  { label: "Valthos (AI Biodefense Startup)", url: "http://s://www.valthos.com" }
];

// Some URLs in the tracker are missing the ':' after https (common spreadsheet typo).
// This normalizer makes the seed list robust without manual cleanup.
function normalizeSeedUrl(url: string): string {
  return url.replace(/^http:\/\/s:\/\//, 'https://').replace(/^https\/\/:/, 'https://');
}

function normalizeTargets(targets: AcademicSeedTarget[]): AcademicSeedTarget[] {
  return targets.map((t) => ({ ...t, url: normalizeSeedUrl(t.url) }));
}

export const ACADEMIC_SEED_TARGETS: AcademicSeedTarget[] = normalizeTargets([
  ...CURATED_SEED_TARGETS,
  ...TRACKER_LAB_SEED_TARGETS,
]);

export function getAcademicSeedTargets() {
  return ACADEMIC_SEED_TARGETS;
}
